services:
  csmt:
    build:
      context: .
      args:
        SERVICE: csmt-api
    ports:
      - "1323:1323"
    restart: unless-stopped
  funny:
    build:
      context: .
      args:
        SERVICE: funny-api
    ports:
      - "2287:2287"
    restart: unless-stopped